### ISSUE TITLE
Paired-end reads

### ISSUE THREAD

**Issue by Midnighter** [tyjo/coptr#5]
Hi,

More of a discussion question. I was wondering if you can say a few more words about the reasoning for this line from the documentation, please?

> For paired end sequencing, it is recommend to only map reads from a single mate-pair.

**Comment by tyjo** [comment]
Paired reads are not independent. Using both mate pairs does not provide much additional information for PTR estimation beyond a single read, while also being a larger computational burden during mapping.

It's worth noting that other tools take a similar approach (e.g. https://github.com/biobakery/MetaPhlAn/wiki/MetaPhlAn-3.0).

**Comment by Midnighter** [comment]
That's certainly intuitive with regard to PTR. I was wondering if having the pairs would help with "placing" the reads, though, when mapping against many genomes?

**Comment by tyjo** [comment]
I'm not sure using paired reads will help during the mapping step, because reads are being mapped to representative genomes from 95% ANI clusters. Consequently, we often aren't mapping reads to the exact strain in the sample. In this setting I'm not sure how much information from paired reads helps achieve a more accurate mapping. Insertions or deletions in a strain relative to the reference could violate assumptions that the read mapper uses to accurately place paired reads.

That being said, you can map paired reads with bowtie2 and pass them to CoPTR. CoPTR will extract one read per mate-pair for downstream steps.

**Comment by Midnighter** [comment]
Awesome, than you for your explanation.
